name: Deployment to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Write private key to file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > prod_private_key.pem
          chmod 600 prod_private_key.pem

      - name: SSH into production server and deploy
        run: |
          sshpass -p "" ssh -o StrictHostKeyChecking=no -i prod_private_key.pem -p ${{ secrets.PROD_PORT }} ${{ secrets.PROD_USERNAME }}@${{ secrets.PROD_HOST }} "
            sudo -s
            ./cicd.sh  # Run cicd.sh script
          "
